// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3RjQqFTIuZ8LB4LmCtIGTFQRxw7pR6Bs',
    appId: '1:243102820200:web:60101f8cc01fb74bc3d8dd',
    messagingSenderId: '243102820200',
    projectId: 'hotelkhujo-37062',
    authDomain: 'hotelkhujo-37062.firebaseapp.com',
    storageBucket: 'hotelkhujo-37062.appspot.com',
    measurementId: 'G-4FZP55HJDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2c7ydCon4AR7yK7QIQiZzasUZ89SUxEA',
    appId: '1:243102820200:android:61a3d406e394939cc3d8dd',
    messagingSenderId: '243102820200',
    projectId: 'hotelkhujo-37062',
    storageBucket: 'hotelkhujo-37062.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3RjQqFTIuZ8LB4LmCtIGTFQRxw7pR6Bs',
    appId: '1:243102820200:web:6027ce8cf036a808c3d8dd',
    messagingSenderId: '243102820200',
    projectId: 'hotelkhujo-37062',
    authDomain: 'hotelkhujo-37062.firebaseapp.com',
    storageBucket: 'hotelkhujo-37062.appspot.com',
    measurementId: 'G-45LDNPS5S8',
  );
}
